GRAPHITI_MCP_URL = "http://localhost:8000/mcp"
BASELINE_MODEL_NAME = "gpt-4o-mini"
GRAPHITI_VDB_CHROMADB_DIR = "./graphiti_vdb_chroma_memory_db"
BASELINE_CHROMADB_DIR = "./baseline_chroma_memory_db"
MLFLOW_TRACKING_URI = "http://localhost:5050"
MLFLOW_EXPERIMENT_NAME = "memory-agents-experiment"
